version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: whattodo-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgreswhattodo
      POSTGRES_DB: whattodo

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
